### ISSUE TITLE
Symbol Relocation Info

### ISSUE THREAD

**Issue by blankwall** [hkkwok/MachOTool#1]
Any update on the symbol relocation info stuff? Was looking to use that in an upcoming project.

**Comment by hkkwok** [comment]
I am still working on it and hopefully have it done sometime around X'mas. (I recently switch job so didn't get to work on it for a couple weeks.)

**Comment by blankwall** [comment]
Ok thanks for reference I found a pretty good implementation here: https://github.com/Vector35/binaryninja-python/blob/master/MachOFile.py
